[theme]
primaryColor = "#6eb52f"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e0ef"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true

[browser]
serverAddress = "localhost" 